FROM ioiox/php-nginx:7.4-alpine
ENV INSTALL false
ENV MODIFY true
ENV VERSION 2.0.7

WORKDIR /

COPY ./ /dujiaoka

COPY ./conf/default.conf /opt/docker/etc/nginx/vhost.conf
COPY ./conf/dujiao.conf /opt/docker/etc/supervisor.d/
COPY ./modify /dujiaoka/modify

WORKDIR /dujiaoka

RUN set -xe \
    && composer install -vvv \
    && chmod +x /dujiaoka/start.sh \
    && chown -R application:application /dujiaoka/ \
    && chmod -R 0755 /dujiaoka/ \
    && mv /dujiaoka/storage /dujiaoka/storage_bak \
    && sed -i "s?\$proxies;?\$proxies=\'\*\*\';?" /dujiaoka/app/Http/Middleware/TrustProxies.php \
    && rm -rf /root/.composer/cache/ /tmp/*

CMD /dujiaoka/start.sh
